### ISSUE TITLE
ユーザー側　検索モーダル

### ISSUE THREAD

**Issue by SEKI-YUTA** [SEKI-YUTA/GEEKCAMP_HACKATHON_20230929#21]
ユーザー側のホーム画面に検索ボタンを設置して、クリック時に左のモーダル、検索結果は右の画面に条件分岐で変わるようにしてください。
検索結果から元の画面に戻る場合は、画像にはないですが、検索モーダルか画面にリセットモーダルを用意して元のホーム画面に戻すかページをリロードして戻すものとします。

検索方法はAPIにリクエスト（`http://localhost:8080/restaurants/1/menus?lower=1000`など、詳しくはREADME参照）から取得する方法でも、Reactのステート上で絞り込みする方法でも構いません。

![image](https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/assets/60034520/756065a1-7716-47bc-bfb8-d7607877157c)

@takeki-99 可能そうならアサインお願いします！！🙇

**Comment by takeki-99** [comment]
okです！
