### ISSUE TITLE
メニュー一覧でカテゴリーでメニュー表示切り替えの実装

### ISSUE THREAD

**Issue by illionillion** [SEKI-YUTA/GEEKCAMP_HACKATHON_20230929#25]
@takeki-99 メニュー一覧取得が完了したらこちらもお願いできますか？

アサインする場合は右側の`Assignees`で自分のアカウントを登録してください〜

カテゴリーのタブには「すべて」の全部を表示するタブも追加してデフォルトでメニュー全部が表示されるようにして欲しいです！！

<img width="740" alt="image" src="https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/assets/60034520/0436e1fe-2f6c-4c96-8d8a-ad3f4995cd38">

**Comment by takeki-99** [comment]
了解です👌
