### ISSUE TITLE
ユーザー側のホーム画面作成

### ISSUE THREAD

**Issue by illionillion** [SEKI-YUTA/GEEKCAMP_HACKATHON_20230929#29]
`/restaurant/:{id}/`（idはレストランテーブルのid）にレストランのメニュー表を表示する画面を作成

URLからidを取得するのには`react-router-dom`の`useParams`を使用して取得できます。
`frontend-react-app/src/features/restaurant/home/UI`の中のConで`useParams`実行してください！
可能そうならオーナー側のホーム画面のコンポーネントを共通化して使ってもいいと思います！！

例として「/restaurant/1」の場合はidが1のレストランのメニュー一覧をfetchで取得

以下、ルーターの部分

<img width="901" alt="image" src="https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/assets/60034520/9b500a8b-a2a8-4aeb-8bbf-d38cebcf67ed">

可能ならアサインお願いします〜🙇 @takeki-99

**Comment by takeki-99** [comment]
okです！
