### ISSUE TITLE
メニューの新規登録モーダルの値段を入力する所の初期の数字が消す事ができない

### ISSUE THREAD

**Issue by SEKI-YUTA** [SEKI-YUTA/GEEKCAMP_HACKATHON_20230929#39]

**Comment by illionillion** [comment]
@SEKI-YUTA https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/pull/36
ここでやったよー

issueたくさん作ったと思うけれど作るならもう少しタイトル短めにして一目でどういうやつか分かるようにした方がいいと思う
他の人が見ても分かるようにdescriptionにスクショ貼るなり詳しく説明書いてほしい

**Comment by illionillion** [comment]
#43 ここで完了
