### ISSUE TITLE
メニュー新規登録モーダルの値段入力に値が0円の時の警告をつける

### ISSUE THREAD

**Issue by SEKI-YUTA** [SEKI-YUTA/GEEKCAMP_HACKATHON_20230929#40]
このモーダルの値段が0円の時はフォーカスが外れた時に値をチェックして警告の表示を出すようにして欲しいです。

`onbBur`のイベントで`e.target.value`の中を見たらその時の値が取れるのでそれで処理できると思います。

<img width="698" alt="image" src="https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/assets/60034520/07dfad27-2475-4fa4-90f7-906ec1b181d1">

**Comment by illionillion** [comment]
@AnonymousinJP このブランチをプルして作業して欲しい〜
https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/pull/36

**Comment by illionillion** [comment]
#43 ここでマージしたので終了
