### ISSUE TITLE
ユーザー側ホーム画面での商品詳細のモーダル

### ISSUE THREAD

**Issue by SEKI-YUTA** [SEKI-YUTA/GEEKCAMP_HACKATHON_20230929#8]
@AnonymousinJP 
ユーザー側のホーム画面（`http://localhost:3000/restaurant/1`）でメニューをクリックした時にメニューの詳細を表示するモーダルを実装してください！！

以下の画像のように、`/src/features/owner/home/UI/Components/MenuVIewModal.tsx`に商品の詳細を表示するモーダルがあるのでこれを再利用して、フッターのボタン類を削除する感じでいいと思います！

`dev`にチェックアウトして、別途`feature-**`ブランチを作成して作業してください🙇

<img width="1024" alt="image" src="https://github.com/SEKI-YUTA/GEEKCAMP_HACKATHON_20230929/assets/60034520/5235e4e4-8dea-4918-b9e6-53780b8c9b66">

**Comment by illionillion** [comment]
#53 closed
